apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: board
resources:
  - 00-namespace.yaml
  - 10-config.yaml
  - 20-postgres.yaml # delete this line if you use a managed/external database
  - 30-board.yaml
  - 40-ingress.yaml
